### ISSUE TITLE
REV toolbar appears for other input views

### ISSUE THREAD

**Issue by Jirka1111** [cjwirth/RichEditorView#12] opened 2015-10-18 15:33 UTC
I have a problem. I have a text field above a REV and when I click on REV, than on my text field, the REV panel is still showing above the keyboard. Is there a way how to lost focus of REV and dissapear of REV panel?

**Comment by cjwirth** [comment] 2015-10-20 01:13
Hmm, I couldn't get this to reproduce in the sample app. What version are you using? Could you maybe make a gif of the problem, or make some sample project where it happens?

**Comment by Jirka1111** [comment] 2015-11-17 16:34
Dear cjwirth,
there is a video of my problem:

https://mega.nz/#!jIg2CbJZ!nQLdk-mUr0PXiuEkbHAzcS_9FItqOUiXIzKsZUgEIms

**Comment by cjwirth** [comment] 2015-11-18 03:53
How are you showing/hiding the toolbar in the first place? 

It looks like you're probably using the KeyboardManager from the sample project? If so, all that does is listen to when the keyboard comes up and down, and moves the toolbar to be above it. It doesn't pay attention to what view is the first responder or not. I wouldn't use the KeyboardManager if you have input views that are not REVs onscreen.

I would suggest setting the _inputAccessoryView_ of the text views instead. Then they shouldn't conflict with each other.

**Comment by Jirka1111** [comment] 2015-11-20 23:51
You are right. I'll try and let you know.

**Comment by cjwirth** [comment] 2015-11-26 08:27
Any updates on this, @Jirka1111? Is it working for you?

**Comment by cjwirth** [comment] 2015-11-28 07:16
Let me know if it's not working. I'm going to close this ticket, because you said I was right :)

**Closed by cjwirth** 2015-11-28 07:16 UTC
