### ISSUE TITLE
Cant share word from RichEditorView

### ISSUE THREAD

**Issue by Estanque** [cjwirth/RichEditorView#14] opened 2015-11-16 11:20 UTC
Hello.

When I try to use "share" button from context menu(long tap on the any word) and choose Twitter or Messages and tap on Cancel button on Share Controller - I cant can no longer interact with application. 
I tried to disable share button by creating UIWebView child with canPerformAction method that returns false but it doesn't work too.

How can I disable button or fix this behaviour?

![hbnvfbbjoik](https://cloud.githubusercontent.com/assets/4593570/11180609/e658df36-8c7d-11e5-9db5-bebfe495f5bf.jpg)

**Comment by cjwirth** [comment] 2015-11-18 04:55
Oh wow, nice catch. This _is_ a problem. 

I haven't found a way to prevent it yet, but I have confirmed that it happens in a sample app with nothing but a web view with a content editable div. Normal divs seem to be OK. 

This is something happening to more than just RichEditorView... I hope we can find a workaround.

**Comment by cjwirth** [comment] 2015-11-21 09:32
I've submit a bug to Apple, as well as listed it on [Open Radar](https://openradar.appspot.com/23641003)

This bug doesn't seem to happen in Safari, so there is probably some kind of way around it :/

**Comment by cjwirth** [comment] 2016-02-06 04:02
Closing this, because it seems to be a problem with the system, and I haven't been able to find a workaround :cry:

**Closed by cjwirth** 2016-02-06 04:02 UTC
