### ISSUE TITLE
add image button and add link button is not see

### ISSUE THREAD

**Issue by lizizi** [cjwirth/RichEditorView#143] opened 2017-11-03 02:17 UTC
the demo's add image button and add link button is not allow to see ,how can i resolve it

**Comment by magonicolas** [comment] 2017-11-15 15:43
Yes, I can't see add image and link as well. Also is it possible to add a Video?

**Comment by cjwirth** [comment] 2017-11-15 15:58
I'm not sure what the problem is here. Are you saying the sample project no longer shows the image and link buttons?

> Also is it possible to add a Video?

This is not currently supported.

**Comment by magonicolas** [comment] 2017-11-15 17:05
Yes, the Sample project when you select swift it no longer shows image and link buttons.

**Comment by swapnalishinde** [comment] 2017-11-16 07:08
I can see the image and link button. Also I am able to add the images.
But large size images are not properly set in editor. Can anyone help on this?

**Comment by mjscarlett** [comment] 2018-01-04 15:37
Not sure if this is the right fix or not, but I found that the length seemed to be calculated to short in RichEditorToolbar.swift.  It seemed to truncate the toolbar images.

I increased the defaultIconWidth to 28 (line 137) and now all the images are appearing.

**Comment by swapnalishinde** [comment] 2018-01-05 07:23
Hey Thanks!
Actually I had tried the same and it worked very well but forgot to update you guys!

**Comment by zczc521** [comment] 2018-01-05 09:32
Hello, there is a way to get the click of the picture callback, I tried to add the onclick method in the JS, but it doesn't work.  你好，有什么办法可以拿到图片的点击回调呢，我尝试在js里面添加了onclick方法，但是不起作用 @cjwirth

**Comment by cjwirth** [comment] 2018-02-04 18:43
> I increased the defaultIconWidth to 28 (line 137) and now all the images are appearing.

This has been merged into master, and will be going out with 5.0.0.

Thanks for looking into this everyone :slightly_smiling_face:

**Closed by cjwirth** 2018-02-04 18:43 UTC
