### ISSUE TITLE
Support for Swift 3.0

### ISSUE THREAD

**Issue by najmul-csebuet** [cjwirth/RichEditorView#88] opened 2016-10-11 04:38 UTC
Hi,
     Can you please upgrade this library to support swift 3.0?
Thank you.

**Comment by cjwirth** [comment] 2016-10-11 14:00
I have a [branch](https://github.com/cjwirth/RichEditorView/tree/swift-3) where I migrated the code to Swift 3, and made some of the APIs a little bit more "swifty." You're free to use it. It probably won't change much between now and when I release it. I just want to make sure there will be no problems with versioning the Swift 2, 2.3, and 3 versions and CocoaPods/Carthage before actually releasing it.

**Comment by najmul-csebuet** [comment] 2016-10-11 18:25
swift 3 branch is showing errors. can you pls check?

**Comment by cjwirth** [comment] 2016-10-11 20:39
Have you tried cleaning, etc? I just created a new sample project and it worked fine.

This is the Podfile I used:
```Ruby
use_frameworks!

target 'sample' do
    pod 'RichEditorView', :git => 'git@github.com:cjwirth/RichEditorView.git', :branch => 'swift-3'
end

```

**Comment by najmul-csebuet** [comment] 2016-10-12 04:42
Trying now, will let you know soon Insha'Allah.

**Comment by laxmanrizecorp** [comment] 2016-10-13 05:44
Hi,  i tried to install pod for swift 3.0. i am getting the below error. 

Pre-downloading: `RichEditorView` from `git@github.com:cjwirth/RichEditorView.git`, branch `swift-3`

[!] Error installing RichEditorView
[!] /usr/bin/git clone git@github.com:cjwirth/RichEditorView.git /var/folders/gf/w8y8xg114fs2715kqmr87r9w0000gn/T/d20161013-3094-mbut3s --template= --single-branch --depth 1 --branch swift-3

Cloning into '/var/folders/gf/w8y8xg114fs2715kqmr87r9w0000gn/T/d20161013-3094-mbut3s'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists

Thanks.

**Comment by cjwirth** [comment] 2016-10-13 14:07
OK, @laxmanrizecorp it seems like that's unlikely a problem with my library but rather your git setup. I'm not 100% of the cause, but you should maybe try making sure your SSH keys are set up correctly.

In the meantime, in you Podfile, you can change the URL of the library from `git@github.com:cjwirth/RichEditorView.git` to `https://github.com/cjwirth/RichEditorView`, and I have a feeling it might work

**Comment by cjwirth** [comment] 2016-10-31 14:18
> swift 3 branch is showing errors. can you pls check?

These errors should be fixed. I didn't realize people were trying to build the project itself, which is something I rarely, if ever, do. I did all the development using CocoaPods through the sample project. Sorry for that. `swift-3` branch should be good now.

**Comment by cjwirth** [comment] 2017-03-04 20:33
The current master branch is now Swift 3. Sorry for being so slow and unresponsive! 🙏

**Closed by cjwirth** 2017-03-04 20:33 UTC
