### ISSUE TITLE
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs

### ISSUE THREAD

**Issue by marcelosampaio** [cjwirth/RichEditorView#211] opened 2019-09-01 14:38 UTC
Dear Developer,

We identified one or more issues with a recent delivery for your app, "Web Laudos" 1.0 (122). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by mehroozkhanpl** [comment] 2019-09-02 07:13
I add library file direct to project. removed pod. and then edit TextEditorView.swift file
I solved this by Using WKWebView. You can check this link and update your code.
"https://gist.github.com/fabfelici/f16f1ce54f00512db7e9ff87270a68f4"

**Comment by az-oolloow** [comment] 2019-09-30 00:21
I tried the above and that code is not even from this editor.

So far in googling this seems to be the most promising fork, installing it right now :) https://github.com/cbess/RichEditorView

**Comment by YoomamaFTW** [comment] 2019-10-15 04:10
Duplicate of #210 
The fork that @az-oolloow works perfectly fine now, and it's tailored for dark mode. Check my comment in that issue for how it's tailored.

**Comment by fukemy** [comment] 2021-05-13 17:34
@az-oolloow i need to disable editing but in "https://github.com/cbess/RichEditorView", the 
```
isEditingEnabled
```
is not found, can u help?

**Closed** 2021-05-14 22:01 UTC
