### ISSUE TITLE
Placeholder doesn't disappear.

### ISSUE THREAD

**Issue by Ying1986** [cjwirth/RichEditorView#51] opened 2016-05-22 19:06 UTC
When I click `orderedList`, placeholder still appears.(without any character)
Only when I input any character, it disappears.

**Comment by cjwirth** [comment] 2016-05-23 00:12
This might be a duplicate of https://github.com/cjwirth/RichEditorView/issues/48

**Closed** 2016-05-23 00:15 UTC
