### ISSUE TITLE
Help Me

### ISSUE THREAD

**Issue by zczc521** [cjwirth/RichEditorView#149] opened 2018-01-05 09:33 UTC
Hello, there is a way to get the click of the picture callback, I tried to add the onclick method in the JS, but it doesn't work. 你好，有什么办法可以拿到图片的点击回调呢，我尝试在js里面添加了onclick方法，但是不起作用 @cjwirth

**Comment by cjwirth** [comment] 2018-02-04 17:15
Closing as a duplicate of https://github.com/cjwirth/RichEditorView/issues/80

I'm not really sure what the problem is, to be honest.

**Closed by cjwirth** 2018-02-04 17:15 UTC
