### ISSUE TITLE
Strange `underline`

### ISSUE THREAD

**Issue by Ying1986** [cjwirth/RichEditorView#59] opened 2016-05-26 11:26 UTC
https://www.dropbox.com/s/x743tqtm3yfobec/UnderLine.mov?dl=0

When I set/unset underline editor strange.

I input **Underline**(1st line) after click `underline`.
And tried unset `underline` and input **new line** (2nd line).
At that time editor insert line breaks without **return** key.

**Comment by cjwirth** [comment] 2016-05-27 01:09
Yeah, that's super weird... 😟 

Are you using the master branch or one of the tagged releases?

**Comment by Ying1986** [comment] 2016-05-27 08:59
I'm using master branch.

**Comment by cjwirth** [comment] 2016-05-27 09:42
Ok, I see... I think I have an idea of why this might be happening -- this might be a bug new in master that wasn't there before.

Try it out with the 3.2.0 tag and tell me what happens. The scroll won't follow the cursor (that's new in master), but this bug might not be there.

**Comment by cjwirth** [comment] 2016-05-29 09:58
Yeah I tried it out on 3.2.0, and it works fine there. I know where the problem is -- it's a bug in the new feature that scrolls the caret into view. I'll see if I can fix it without breaking the scrolling feature.

**Comment by cjwirth** [comment] 2016-06-01 13:57
Fixed this on the `develop` branch, so take a look if you have time 😃 

I think it should work, but tell me if you find anything that broke, in particular the scrolling.

**Comment by cjwirth** [comment] 2016-06-26 08:37
ping?

**Comment by cjwirth** [comment] 2016-07-03 23:31
Closing this issue, because I think it's fixed, and there's been no update from the OP.

Let me know if it's not fixed for you when you use `develop`, and reopen the issue. I'll take another look 👍

**Closed by cjwirth** 2016-07-03 23:31 UTC
Labels: bug
