### ISSUE TITLE
cannot remove placeholder when insert image tag

### ISSUE THREAD

**Issue by yosei-yamagishi** [cjwirth/RichEditorView#117] opened 2017-04-20 08:33 UTC
# problem
if you insert only image tag, don't remove placeholder.
<img width="383" alt="2017-04-20 17 26 42" src="https://cloud.githubusercontent.com/assets/22518469/25221016/9623fe04-25ee-11e7-812a-7045ce1a13d4.png">

# trying (rich__editor.js)
maybe following method condition is not good 
```
RE.updatePlaceholder = function() {
    if (RE.editor.textContent.length > 0) { // ←this part
        RE.editor.classList.remove("placeholder");
    } else {
        RE.editor.classList.add("placeholder");
    }
};
```

i tryed following code. 
```rich__editor.js
RE.updatePlaceholder = function() {
    if (RE.editor.innerHTML.length > 0) { // ←this part
        RE.editor.classList.remove("placeholder");
    } else {
        RE.editor.classList.add("placeholder");
    }
};
```
but when i was remove image tag,don't add placeholder.
because \<br\> left. i don't resolve it. please fix it!!

**Comment by cjwirth** [comment] 2017-06-17 17:35
This problem exists for more than just images. For example, it also happens with newlines, so you have `<div><br></div>`. You're right that that condition is not the best. There's probably some way to see if there is any non-text content inside a div.

**Comment by cjwirth** [comment] 2017-07-08 18:52
Closing this as a duplicate of https://github.com/cjwirth/RichEditorView/issues/91

**Closed by cjwirth** 2017-07-08 18:52 UTC
